language: node_js
node_js:
  - "0.10"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --production -g bower
  - bower install
before_script:
  - ember server --environment test &
  - sleep 3
after_script:
  - make report-cover
addons:
  firefox: "30.0"
