---
language: node_js

addons:
  firefox: "32.0"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install -g bower
  - npm install
  - bower install

before_script:
  - ember server --environment test &
  - sleep 10

script:
  - npm test

after_script:
  - make cover-post
