language: node_js
node_js:
    - "0.10"
before_install:
    - npm install -g bower
    - bower install
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1440x900x32"
    - sleep 5
